name: My main workflows

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  # call-workflow-1:
  #     uses: ./.github/workflows/workflow-1.yml
  # call-workflow-2:
  #     uses: ./.github/workflows/workflow-2.yml
  deploy:
    runs-on: ubuntu-latest
    # needs: [call-workflow-1, call-workflow-2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Allure history
        if: success() || failure()
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Prepare data for summary page
        if: success() || failure()
        run: |
          node extractData.js ${{github.run_number}} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          echo '---->' && cd allure-results-ut && ls && echo 'you see list json file'

      - name: Generate Allure report for Android
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-detox
          allure_report: ${{ github.run_number }}-android
          allure_history: allure-history-android
          keep_reports: 5
          gh_pages: gh-pages/allure-history-android

      - name: Generate Allure report for iOS
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-detox
          allure_report: ${{ github.run_number }}-ios
          allure_history: allure-history-ios
          keep_reports: 5
          gh_pages: gh-pages/allure-history-ios

      - name: Generate Allure report for UT
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-ut
          allure_report: ${{ github.run_number }}-ut
          allure_history: allure-history-ut
          keep_reports: 5
          gh_pages: gh-pages/allure-history-ut

 

      - name: Prepare github paging
        if: success() || failure()
        run: |
          mkdir public
          cp -r allure-history-ut allure-history-android allure-history-ios public
          cp report.json index.html script.js loadData.js style.css public

      - name: Deploy report to Github Pages
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
