name: My main workflows

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  # call-workflow-1:
  #     uses: ./.github/workflows/workflow-1.yml
  # call-workflow-2:
  #     uses: ./.github/workflows/workflow-2.yml
  deploy:
    runs-on: ubuntu-latest
    # needs: [call-workflow-1, call-workflow-2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Allure history
        if: success() || failure()
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace - Detox
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-detox
          allure_report: ${{ github.run_number }}-detox
          allure_history: allure-history-detox
          keep_reports: 5
          gh_pages: gh-pages/allure-history-detox

      - name: Allure Report action from marketplace - UT
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-ut
          allure_report: ${{ github.run_number }}-ut
          allure_history: allure-history-ut
          keep_reports: 5
          gh_pages: gh-pages/allure-history-ut

      - name: Display structure of downloaded files
        run: |
          pwd && echo '------>' && ls 
          echo '-----> you see the list of report'

      - name: Prepare github paging
        run: |
          mkdir public
          cp -r allure-history-ut public
          cp -r allure-history-detox public

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
