name: My main workflows

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  call-workflow-1:
      uses: ./.github/workflows/workflow-1.yml
  call-workflow-2:
      uses: ./.github/workflows/workflow-2.yml
      # needs: [call-workflow-1]
