name: My main workflows

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  # call-workflow-1:
  #     uses: ./.github/workflows/workflow-1.yml
  # call-workflow-2:
  #     uses: ./.github/workflows/workflow-2.yml
  deploy:
    runs-on: ubuntu-latest
    # needs: [call-workflow-1, call-workflow-2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: allure-results-detox
      #     path: allure-results-detox
      #     retention-days: 10

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: allure-results-ut
      #     path: allure-results-ut
      #     retention-days: 10

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: result
      #     path: news

      - name: Allure Report action from marketplace - Detox
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-detox
          allure_report: ${{ github.run_number }}
          allure_history: allure-history-detox
          keep_reports: 5

      - name: Allure Report action from marketplace - UT
        if: success() || failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results-ut
          allure_report: ${{ github.run_number }}
          allure_history: allure-history-ut
          keep_reports: 5

      - name: Display structure of downloaded files
        run: |
          pwd && echo '------>' && ls 
          echo '-----> you see the list of report'

      # - name: Deploy report to Github Pages
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: news
