name: My main workflows

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  call-workflow-1:
      uses: ./.github/workflows/workflow-1.yml
  call-workflow-2:
      uses: ./.github/workflows/workflow-2.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [call-workflow-1, call-workflow-2]
    steps:
       - uses: actions/upload-artifact@v2
         with:
          name: result
          path: folder
          retention-days: 10

       - uses: actions/download-artifact@v3
         with:
          name: result
          path: news

       - name: Display structure of downloaded files
         run: |
             pwd && ls
             cd news && ls && echo '-----> you see the list of report'

       - name: Deploy report to Github Pages
         uses: peaceiris/actions-gh-pages@v2
         env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: news
  
